/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 */
export const roles = {
    /**
     * Project manager
     */
    projectManager: {
        codename: 'project-manager',
        id: 'ab3560ad-0e48-49ca-b9c7-6964e8a1b6e6',
        name: 'Project manager'
    }
} as const;
